parameters:
#    km_admin.example.class: km\AdminBundle\Example

services:
#    km_admin.example:
#        class: %km_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
