index:
    path:     /
    defaults: { _controller: kmPageBundle:Page:index }

info:
    path:     /info
    defaults: { _controller: kmPageBundle:Page:info }

location:
    path:     /location
    defaults: { _controller: kmPageBundle:Page:location }

kontakt:
    path:     /kontakt
    defaults: { _controller: kmPageBundle:Page:kontakt }

impressum:
    path:     /impressum
    defaults: { _controller: kmPageBundle:Page:impressum }

bands:
    resource: "@kmPageBundle/Resources/config/Bands/routing.yml"
    prefix:   /bands